---
x-build: &build
  image: "${DOCKER_REPO}/${DOCKER_REGISTRY}/import-jobs:${VERSION:-1.0.0}"
  build:
    context: "../"
    dockerfile: "develop/Dockerfile"
  volumes:
    - "./nautobot_config.py:/opt/nautobot/nautobot_config.py"
    - "../:/source"
  env_file:
    - ".env"
  tty: true

services:

  docs:
    entrypoint: "mkdocs serve -v -a 0.0.0.0:8080"
    ports:
      - "8001:8080"
    <<: *build
