---
# This file can be used to configure pre-commit hooks for this repository.
# To use:
#    pip install pre-commit
#    pre-commit install
repos:
  - repo: "local"
    hooks:
      - id: "run lint"
        name: "run lint"
        entry: "make lint-fix"
        language: "system"
        pass_filenames: false
